import Head from "next/head";
import { useState } from "react";
import arr from "../data";

export default function Home() {
  let [inputVal, setInputVal] = useState("");
  const [index, setIndex] = useState(0);
  let quote = arr[0].split(" ");

  
  const checking = (e) => {
    if (inputVal.trim() == quote[index]) {
      console.log("done", index);
      setInputVal("");
      setIndex(index + 1);
    }
  };

  return (
    <div className="">
      <Head>
        <title>BanglaTypeRacer</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <main className="flex justify-center items-center w-full h-screen bg-black">
        <div className="w-[70%] bg-[#0d1013] box-border p-5 rounded-md">
          <h2 className="m-5 text-gray-500">
            {quote.map((each, i) => (
              <span key={i}>{each + " "}</span>
            ))}
          </h2>
          <div className="p-5 w-full">
            <input
              onKeyUp={checking}
              onChange={(e) => setInputVal(e.target.value)}
              value={inputVal}
              className="p-2 w-full text-white bg-black rounded-md"
              type="text"
            />
          </div>
        </div>
      </main>
    </div>
  );
}
